In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Load the Dataset**

In [7]:
import pandas as pd

file_path = r"C:\Retail supply chain\Data\DataCoSupplyChainDataset.csv"
df = pd.read_csv(file_path, encoding='ISO-8859-1')

df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

**DataSet overview**

In [11]:
df.shape

(180519, 53)

In [12]:
df.describe()

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Price,Product Status
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180516.000000,180519.000000,180519.000000,...,180519.000000,180519.000000,180519.000000,180519.000000,24840.000000,180519.000000,180519.000000,0.0,180519.000000,180519.0
mean,3.497654,2.931847,21.974989,183.107609,0.548291,31.851451,6691.379495,35921.126914,5.443460,29.719955,...,2.127638,203.772096,183.107609,21.974989,55426.132327,692.509764,31.851451,NaN,141.232550,0.0
std,1.623722,1.374449,104.433526,120.043670,0.497664,15.640064,4162.918106,37542.461122,1.629246,9.813646,...,1.453451,132.273077,120.043670,104.433526,31919.279101,336.446807,15.640064,NaN,139.732492,0.0
min,0.000000,0.000000,-4274.979980,7.490000,0.000000,2.000000,1.000000,603.000000,2.000000,-33.937553,...,1.000000,9.990000,7.490000,-4274.979980,1040.000000,19.000000,2.000000,NaN,9.990000,0.0
25%,2.000000,2.000000,7.000000,104.379997,0.000000,18.000000,3258.500000,725.000000,4.000000,18.265432,...,1.000000,119.980003,104.379997,7.000000,23464.000000,403.000000,18.000000,NaN,50.000000,0.0
50%,3.000000,4.000000,31.520000,163.990005,1.000000,29.000000,6457.000000,19380.000000,5.000000,33.144863,...,1.000000,199.919998,163.990005,31.520000,59405.000000,627.000000,29.000000,NaN,59.990002,0.0
75%,5.000000,4.000000,64.800003,247.399994,1.000000,45.000000,9779.000000,78207.000000,7.000000,39.279617,...,3.000000,299.950012,247.399994,64.800003,90008.000000,1004.000000,45.000000,NaN,199.990005,0.0
max,6.000000,4.000000,911.799988,1939.989990,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,...,5.000000,1999.989990,1939.989990,911.799988,99301.000000,1363.000000,76.000000,NaN,1999.989990,0.0

In [13]:
df.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Id',
       'Customer Lname', 'Customer Password', 'Customer Segment',
       'Customer State', 'Customer Street', 'Customer Zipcode',
       'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market',
       'Order City', 'Order Country', 'Order Customer Id',
       'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id',
       'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Order Zipcode', 'Product Card Id', 'Product Category Id',
       'Product Description', 'Product Image', 'Product Name', 'Product Price',
       'Product Status', 'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='object')

In [14]:
df.info

<bound method DataFrame.info of             Type  Days for shipping (real)  Days for shipment (scheduled)  \
0          DEBIT                         3                              4
1       TRANSFER                         5                              4
2           CASH                         4                              4
3          DEBIT                         3                              4
4        PAYMENT                         2                              4
...          ...                       ...                            ...
180514      CASH                         4                              4
180515     DEBIT                         3                              2
180516  TRANSFER                         5                              4
180517   PAYMENT                         3                              4
180518   PAYMENT                         4                              4

        Benefit per order  Sales per customer   Delivery Status  \
0               91.250000          314.640015  Advance shipping
1             -249.089996          311.359985     Late delivery
2             -247.779999          309.720001  Shipping on time
3               22.860001          304.809998  Advance shipping
4              134.210007          298.250000  Advance shipping
...                   ...                 ...               ...
180514          40.000000          399.980011  Shipping on time
180515        -613.770019          395.980011     Late delivery
180516         141.110001          391.980011     Late delivery
180517         186.229996          387.980011  Advance shipping
180518         168.949997          383.980011  Shipping on time

        Late_delivery_risk  Category Id   Category Name Customer City  ...  \
0                        0           73  Sporting Goods        Caguas  ...
1                        1           73  Sporting Goods        Caguas  ...
2                        0           73  Sporting Goods      San Jose  ...
3                        0           73  Sporting Goods   Los Angeles  ...
4                        0           73  Sporting Goods        Caguas  ...
...                    ...          ...             ...           ...  ...
180514                   0           45         Fishing      Brooklyn  ...
180515                   1           45         Fishing   Bakersfield  ...
180516                   1           45         Fishing       Bristol  ...
180517                   0           45         Fishing        Caguas  ...
180518                   0           45         Fishing        Caguas  ...

       Order Zipcode Product Card Id Product Category Id  Product Description  \
0                NaN            1360                  73                  NaN
1                NaN            1360                  73                  NaN
2                NaN            1360                  73                  NaN
3                NaN            1360                  73                  NaN
4                NaN            1360                  73                  NaN
...              ...             ...                 ...                  ...
180514           NaN            1004                  45                  NaN
180515           NaN            1004                  45                  NaN
180516           NaN            1004                  45                  NaN
180517           NaN            1004                  45                  NaN
180518           NaN            1004                  45                  NaN

                                            Product Image  \
0            http://images.acmesports.sports/Smart+watch
1            http://images.acmesports.sports/Smart+watch
2            http://images.acmesports.sports/Smart+watch
3            http://images.acmesports.sports/Smart+watch
4            http://images.acmesports.sports/Smart+watch
...                                                   ...
180514  http://images.acmesports.sports/Field+%26+Stre...
180515  http://images.acmesports.sports/Field+%26+Stre...
180516  http://images.acmesports.sports/Field+%26+Stre...
180517  http://images.acmesports.sports/Field+%26+Stre...
180518  http://images.acmesports.sports/Field+%26+Stre...

                                     Product Name Product Price  \
0                                    Smart watch     327.750000
1                                    Smart watch     327.750000
2                                    Smart watch     327.750000
3                                    Smart watch     327.750000
4                                    Smart watch     327.750000
...                                           ...           ...
180514  Field & Stream Sportsman 16 Gun Fire Safe    399.980011
180515  Field & Stream Sportsman 16 Gun Fire Safe    399.980011
180516  Field & Stream Sportsman 16 Gun Fire Safe    399.980011
180517  Field & Stream Sportsman 16 Gun Fire Safe    399.980011
180518  Field & Stream Sportsman 16 Gun Fire Safe    399.980011

       Product Status shipping date (DateOrders)   Shipping Mode
0                   0             2/3/2018 22:56  Standard Class
1                   0            1/18/2018 12:27  Standard Class
2                   0            1/17/2018 12:06  Standard Class
3                   0            1/16/2018 11:45  Standard Class
4                   0            1/15/2018 11:24  Standard Class
...               ...                        ...             ...
180514              0             1/20/2016 3:40  Standard Class
180515              0             1/19/2016 1:34    Second Class
180516              0            1/20/2016 21:00  Standard Class
180517              0            1/18/2016 20:18  Standard Class
180518              0            1/19/2016 18:54  Standard Class

[180519 rows x 53 columns]>